[project]
name = "vllm-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "transformers>=4.57.1",
    "vllm>=0.11.0",
]


[[index]]
url = "https://pypi.mirrors.ustc.edu.cn/simple/"
default = true
